# Generated by Django 5.1.1 on 2024-09-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0002_aiagent_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='application_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
