# Generated by Django 5.1.1 on 2024-09-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0003_aiagent_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='bot_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
