# Generated by Django 5.1.1 on 2024-10-04 01:54

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0006_aiagenttask'),
    ]

    operations = [
        VectorExtension()
    ]
