# Generated by Django 5.1.1 on 2024-10-04 01:56

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0007_auto_20241004_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai_agents.coderepository')),
            ],
        ),
    ]
