# Generated by Django 5.1.1 on 2024-10-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0008_coderepository_codefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='file_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
