# Generated by Django 5.1.1 on 2024-10-04 02:33

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0009_codefile_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=10, null=True),
        ),
    ]
