# Generated by Django 5.1.1 on 2024-10-04 02:34

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0010_alter_codefile_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1024, null=True),
        ),
    ]
