# Generated by Django 5.1.1 on 2024-10-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0011_alter_codefile_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codefile',
            name='repository',
        ),
        migrations.AddField(
            model_name='codefile',
            name='repository',
            field=models.ManyToManyField(related_name='code_files', to='ai_agents.coderepository'),
        ),
    ]
