# Generated by Django 5.1.1 on 2024-10-04 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0012_remove_codefile_repository_codefile_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codefile',
            name='repository',
        ),
        migrations.AddField(
            model_name='codefile',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ai_agents.coderepository'),
        ),
    ]
