# Generated by Django 5.1.1 on 2024-09-26 23:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
