# Generated by Django 5.1.1 on 2024-10-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_message_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
