name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.2]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create vector extension
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d github_actions -c "CREATE EXTENSION IF NOT EXISTS vector;"
      - name: Run Tests
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
        run: |
          python manage.py test